DROP TABLE IF EXISTS "UserItemProgresses" CASCADE;
DROP TABLE IF EXISTS "Chunks" CASCADE;
DROP TABLE IF EXISTS "AssessmentItems" CASCADE;
DROP TABLE IF EXISTS "TokenTransactions" CASCADE;
DROP TABLE IF EXISTS "Documents" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Plans" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
